language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing to install"

before_script:
  - echo "no before scripts actions"

script:
  - docker --version 
  - docker build -t udagram-frontend --build-arg API_HOST=$API_HOST .
  - docker tag udagram-frontend jazracherif/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jazracherif/udagram-frontend